#!/usr/bin/env python3

import os
import sys

def main(d):
  count = 0
  for (dp, dn, fs) in os.walk(d):
    for f in fs:
      if f.lower().endswith('.jpg'):
        count += 1
  print(count)

if __name__ == '__main__':
  main(sys.argv[1])
